name: eth_hunter
description: "A polished Flutter desktop application for ETH wallet scanning."
publish_to: 'none' 

# MODIFICATION: Updated version to 1.0.1 and build number to 2.
version: 1.0.1+2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Theming
  system_theme: ^3.0.0 
  flutter_svg: ^2.0.10+1
  dynamic_color: ^1.7.0
  
  # Backend & Logic
  web3dart: ^2.7.1 
  http: ^1.2.1
  
  # State Management
  provider: ^6.1.2

  # Desktop Specific
  window_manager: ^0.5.0 
  bitsdojo_window: ^0.1.6 
  
  # Storage & Utils
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  url_launcher: ^6.3.0 
  path: ^1.9.0
  
  # MODIFICATION: Added package_info_plus to read the app version dynamically.
  package_info_plus: ^8.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/social-media/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400