name: eth_hunter
description: "A polished Flutter desktop application for ETH wallet scanning."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Theming
  system_theme: ^3.0.0 
  flutter_svg: ^2.0.10+1
  dynamic_color: ^1.7.0
  
  # Backend & Logic
  web3dart: ^2.7.1 
  http: ^1.2.1
  
  # State Management
  provider: ^6.1.2

  # Desktop Specific
  window_manager: ^0.5.0 
  bitsdojo_window: ^0.1.6 
  
  # Storage & Utils
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  url_launcher: ^6.3.0 
  path: ^1.9.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/social-media/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

# Full configuration for the launcher icon generator.
flutter_launcher_icons:
  # The image_path is used for all platforms unless overridden.
  image_path: "assets/icons/app-hq.png"
  
  # Android specific settings
  # By removing the adaptive_icon_background and adaptive_icon_foreground keys,
  # we are telling the generator to create a legacy, non-adaptive icon.
  android: true 

  # iOS specific settings
  ios: true

  # Windows specific settings
  windows:
    generate: true
    image_path: "assets/icons/app-hq.png"
    icon_size: 256